name: SMPBotPlugin
version: ${project.version}
main: me.lianecx.smpbotplugin.SMPBotPlugin
api-version: 1.17
authors: [ Lianecx ]
description: The official minecraft plugin to connect with the SMP Minecraft Bot